esphome:
  name: cyberq-controller
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
ota:

logger:

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600

# Custom CyberQ component
external_components:
  - source:
      type: local
      path: components
    components: [cyberq]

cyberq:
  id: cyberq_controller
  uart_id: uart_bus

# Sensors for reading values
sensor:
  - platform: cyberq
    cyberq_id: cyberq_controller
    pit1_temperature:
      name: "Pit 1 Temperature"
      unit_of_measurement: "°F"
      accuracy_decimals: 1
    update_interval: 5s

  - platform: cyberq
    cyberq_id: cyberq_controller
    pit2_temperature:
      name: "Pit 2 Temperature"
      unit_of_measurement: "°F"
      accuracy_decimals: 1
    update_interval: 5s

  - platform: cyberq
    cyberq_id: cyberq_controller
    food1_temperature:
      name: "Food 1 Temperature"
      unit_of_measurement: "°F"
      accuracy_decimals: 1
    update_interval: 5s

  - platform: cyberq
    cyberq_id: cyberq_controller
    food2_temperature:
      name: "Food 2 Temperature"
      unit_of_measurement: "°F"
      accuracy_decimals: 1
    update_interval: 5s

  - platform: cyberq
    cyberq_id: cyberq_controller
    fan1_speed:
      name: "Fan 1 Speed"
      accuracy_decimals: 1
    update_interval: 5s

  - platform: cyberq
    cyberq_id: cyberq_controller
    fan2_speed:
      name: "Fan 2 Speed"
      accuracy_decimals: 1
    update_interval: 5s

# Number controls for setting values
number:
  - platform: cyberq
    cyberq_id: cyberq_controller
    pit1_setpoint:
      name: "Pit 1 Setpoint"
      min_value: 0
      max_value: 500
      step: 1
      unit_of_measurement: "°F"

  - platform: cyberq
    cyberq_id: cyberq_controller
    pit2_setpoint:
      name: "Pit 2 Setpoint"
      min_value: 0
      max_value: 500
      step: 1
      unit_of_measurement: "°F"

  - platform: cyberq
    cyberq_id: cyberq_controller
    food1_setpoint:
      name: "Food 1 Setpoint"
      min_value: 0
      max_value: 500
      step: 1
      unit_of_measurement: "°F"

  - platform: cyberq
    cyberq_id: cyberq_controller
    food2_setpoint:
      name: "Food 2 Setpoint"
      min_value: 0
      max_value: 500
      step: 1
      unit_of_measurement: "°F"

